### ISSUE TITLE
Probably unintentional leaking of optimization changes

### ISSUE THREAD

**Issue by Yehouda** [rtoy/f2cl#1] opened 2023-06-05 13:39 UTC
https://github.com/rtoy/f2cl/blob/a0352cc7e652bff6394ede08c3d9d169963e8780/src/f2cl2.l#L16

The **eval-whe**n when includes **load** evaluates the form at load time, which in this case means doing the call ** (proclaim '(optimize (speed 3) (safety 1)))** at load time. That is a bad idea, because it means that after loading this fiile, anything that doesn't explicitly sets the **optimize safety**  and **speed** level will be compiled  with these setting rather than the default settings.

The other sub-form in the same **eval-when** form, the call to **optimize** with **special**, should happen at load time. So the right fix is to split these to two forms:
```
(eval-when (compile) (proclaim '(optimize (speed 3) (safety 1))))

(eval-when (compile load eval)
  (proclaim '(special *intrinsic-function-names* *external-function-names*
	      *subprog_name* *subprog-stmt-fns*
	      *functions-used*)))
```

**Comment by rtoy** [comment] 2023-06-05 14:33
Thanks for pointing this out.  I tried to look at the history of this.  I tmight go back to the original f2cl version.  The logs aren't helpful.

It probably wouldn't be horrible these days to remove the `optimize` declaration.

I should probably also make a note that the canonical repo is https://gitlab.common-lisp.net/f2cl/f2cl and this is a mirror.  This repo is out-of-date, so I need to update it.  Nevertheless the canonical repo has exactly the same issue.

If you discover anything else, please let me know!  I really appreciate it.

**Comment by rtoy** [comment] 2023-07-16 13:24
Filed https://gitlab.common-lisp.net/f2cl/f2cl/-/issues/8 to track the issue in the main repo

**Comment by rtoy** [comment] 2023-07-16 14:41
Fixed in upstream repo with https://gitlab.common-lisp.net/f2cl/f2cl/-/commit/a3dabbe429ff2fe6039a60c2546d287b4157f546

I'll need to update this mirror with the changes, but the issue is fixed as you suggested.

Thanks!

**Closed as completed by rtoy** 2023-07-16 14:41 UTC
